### ISSUE TITLE
No error message if any of the entry points of webpack does not exist

### ISSUE THREAD

**Issue by tqmukas** [wix/wix-node-build#2]

**Comment by mastertheblaster** [comment]
Got exactly the same today. Struggled a little bit, until found a root cause.

**Comment by maxaon** [comment]
Added info in https://github.com/wix/wix-node-build/pull/4 via debug message.
Enabled by env variable ```DEBUG=wix*```

**Comment by yanivefraim** [comment]
Moved to https://github.com/wix-private/wix-js-stack/issues/385
