### ISSUE TITLE
separateCss: false not injecting the styles in header

### ISSUE THREAD

**Issue by felixmosh** [wix/wix-node-build#6]
when you define `separateCss: false` in package.json, the js bundle should inject the styles inline. 
instead it addes link tag `<link rel="stylesheet" href="blob:http://localhost:3000/d70590c4-76e2-46e9-86dc-3bf23f68caf7">`.
The problem with that, is that TPAs needs inline css in the editor in order to enable Editor style changes.

I`ve investigated it, and it because of sourcemap of cssLoader.
```javascript
const cssLoaderOptions = {
    modules: true,
    camelCase: true,
    sourceMap: true, // should replaced with sourceMap: !!extractCSS,
    localIdentName: '[path][name]__[local]__[hash:base64:5]'
};
```

**Comment by yanivefraim** [comment]
Moved to private
